\documentclass[a4paper]{article}
%\VignetteIndexEntry{Plotting Haplotype Networks}
%\VignettePackage{pegas}
\usepackage[utf8]{inputenc}
\usepackage{fancyvrb}
\usepackage{color}

\newcommand{\code}{\texttt}
\newcommand{\loci}{\code{"loci"}}
\newcommand{\NA}{\code{NA}}
\newcommand{\pkg}{\textsf}
\newcommand{\ape}{\pkg{ape}}
\newcommand{\pegas}{\pkg{pegas}}

\author{Emmanuel Paradis}
\title{Plotting Haplotype Networks with \pegas}

\begin{document}

\maketitle
\tableofcontents

\vspace{1cm}

\setkeys{Gin}{width=\textwidth}
<<echo=false,quiet=true>>=
options(width=60)
@

\section{Background}

\subsection{Layout Algorithm}

<<>>=
library(pegas)#, lib.loc = "~/tmp/pegas.Rcheck")
data(woodmouse)
d <- dist.dna(woodmouse, "N")
nt <- rmst(d, quiet = TRUE)
@

\section{New Features in \pegas\ 1.0}

\subsection{Improved ``Replotting''}

\subsection{Haplotype Symbol Shapes}

The area of a disc is $\pi r^2$ with $r$ being the radius of the disc, so if
we want the area of the symbols to be proportional to \code{size}, we
should square-root them. However, in practice this masks differences
if most values in \code{size} are not very different (see
below). Instead, the diameters of the symbols ($2r$) are equal to the
values in \code{size}. If these are very heterogeneous, they could be
transformed with \code{size = sqrt(...} keeping in mind that the legend
will be on this new scale.

<<fig=true>>=
par(xpd = TRUE)
size <- c(1, 3, 5, 10)
x <- c(0, 5, 10, 20)

plot(0, 0, type="n", xlim=c(-2, 30), asp=1, bty="n", ann=FALSE)
other.args <- list(y = -5, inches = FALSE, add = TRUE,
                   bg = rgb(1, 1, 0, .3))
o <- mapply(symbols, x = x, circles = sqrt(size / pi),
            MoreArgs = other.args)
other.args$y <- 5
o <- mapply(symbols, x = x, circles = size / 2,
            MoreArgs = other.args)
text(x, -1, paste("size =", size), font = 2, col = "blue")
text(30, -5, expression("circles = "*sqrt(size / pi)))
text(30, 5, "circles = size / 2")
@

\noindent For squares and diamonds, their areas are equal to the discs for the
same values given to \code{size}:

<<fig=true>>=
x <- c(0, 6, 13, 25)
plot(0, 0, type="n", xlim=c(-2, 30), asp=1, bty="n", ann=FALSE)
other.args$y <- 0
o <- mapply(symbols, x = x, circles = size/2, MoreArgs = other.args)
other.args$col <- "black"
other.args$add <- other.args$inches <- NULL
o <- mapply(pegas:::square, x = x, size = size, MoreArgs = other.args)
o <- mapply(pegas:::diamond, x = x, size = size, MoreArgs = other.args)
text(x, -7, paste("size =", size), font = 2, col = "blue")
@

\noindent A diamond is a square rotated 45\textdegree\ around its center.

\subsection{Optionss}


<<fig=true>>=
plot(nt, size = 2)
@


<<fig=true>>=
setHaploNetOptions(haplotype.inner.color = "#CCCC4D",
                   haplotype.outer.color = "#CCCC4D",
                   show.mutation = 3, labels = FALSE)
plot(nt, size = 2)
@

<<fig=true>>=
setHaploNetOptions(haplotype.inner.color = "blue",
                   haplotype.outer.color = "blue",
                   show.mutation = 1)
par(bg = "yellow3")
plot(nt, size = 2)
@

<<fig=true>>=
setHaploNetOptions(haplotype.inner.color = "navy",
                   haplotype.outer.color = "navy")
par(bg = "lightblue")
plot(nt, size = 2)
@

\end{document}

